# Generated by Django 2.2.6 on 2020-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200824_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='url',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
