# Generated by Django 2.2.6 on 2020-08-24 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20200824_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='bg_color',
            field=models.CharField(default='dark', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='asked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
