# Generated by Django 2.2.6 on 2020-08-28 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0013_auto_20200826_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.CharField(default='de3a167233a09631dff1f90b0d2c4b76e8238e30', max_length=32),
        ),
        migrations.CreateModel(
            name='AnswerLiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
