# Generated by Django 2.2.6 on 2020-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20200828_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.CharField(default='69ba51d144c9485ffa2ea684c76e8af7446e81d8', max_length=32),
        ),
    ]
