# Generated by Django 2.2.6 on 2020-09-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20200901_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.CharField(default='9b5f751f738b82f1cebb42d89f2fd5fa99f3d2d0', max_length=32),
        ),
    ]
