# Generated by Django 2.2.6 on 2020-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20200902_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.CharField(default='29f919eb0e831d3355480000d1de79a4158e5a9f', max_length=32),
        ),
    ]
