# Generated by Django 2.2.6 on 2020-09-09 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=256)),
                ('bg_color', models.CharField(default='#000000', max_length=50)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='A Short Bio about yourself', max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('profile_picture', smartfields.fields.ImageField(blank=True, default='', max_length=255, upload_to='static/images/profile_picture')),
                ('experience', models.PositiveIntegerField(help_text='Exp. in years')),
                ('points', models.PositiveIntegerField(default=0)),
                ('followers', models.ManyToManyField(blank=True, to='accounts.UserProfile')),
                ('follows', models.ManyToManyField(blank=True, related_name='following', to='accounts.UserProfile')),
                ('languages', models.ManyToManyField(to='accounts.ProgrammingLanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
