# Generated by Django 2.2.6 on 2020-09-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', max_length=255, upload_to='static/images/profile_picture'),
        ),
    ]
