# Generated by Django 3.0 on 2020-10-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201019_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='AskaDev', max_length=256),
            preserve_default=False,
        ),
    ]
