# Generated by Django 3.0 on 2020-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200822_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', max_length=255, upload_to='static/images/profile_picture'),
        ),
    ]
