# Generated by Django 2.2.6 on 2020-09-02 12:59

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200901_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=smartfields.fields.ImageField(blank=True, default='', max_length=255, upload_to='static/images/profile_picture'),
        ),
    ]
